### ISSUE TITLE
MUSH Audio engine incompatibility

### ISSUE THREAD

**Issue by xana43** [scswinter/MultiTweaks#2]
I've already reported this to Mushroomcake28, but I also want to see if it's possible to get a fix from here as well.
![1627496784430](https://user-images.githubusercontent.com/25046370/127380980-736f658d-d1e0-48f9-a277-f45d7462b7eb.png)

is the issue that i'm currently having with this plugin. 

(at the time of writing this I just got word that Musroomcake28 can't implement a fix right now) so maybe look in to it?
I'm not sure how plugins really work (I'm experienced in javascript, but not with the RPGmaker codebase so I have no clue how anything works)

**Comment by scswinter** [comment]
Mush changes a lot the audio system. Please, deactivate all the audio options of this plugin, as MUSH does them better, and put this plugin before the MUSH. It should work.
